var breakfast = [
  {
    id: "1",
    name: "Begal and Cream Cheese",
    category: "breakfast",
    img: "https://i.postimg.cc/gJdbjrY2/breakfast1.png",
    description: "how we dream about our future",
    price: 23.99,
  },
  {
    id: "2",
    name: "Breakfast Sandwitch",
    category: "breakfast",
    img: "https://i.postimg.cc/VNQ3Z50W/breakfast2.png",
    description: "how we dream about our future",
    price: 10.99,
  },
  {
    id: "3",
    name: "Baked Chicken",
    category: "breakfast",
    img: "https://i.postimg.cc/YqvZpQ1x/breakfast3.png",
    description: "how we dream about our future",
    price: 6.99,
  },
  {
    id: "4",
    name: "Eggs Benedict",
    category: "breakfast",
    img: "https://i.postimg.cc/9FsSzzbH/breakfast4.png",
    description: "how we dream about our future",
    price: 8.99,
  },
  {
    id: "5",
    name: "Toast Croissant Fried Egg",
    category: "breakfast",
    img: "https://i.postimg.cc/XYMH4mNV/breakfast5.png",
    description: "how we dream about our future",
    price: 12.99,
  },
  {
    id: "6",
    name: "Food Breakfast Egg Toast Brunch",
    category: "breakfast",
    img: "https://i.postimg.cc/fbCB7bcL/breakfast6.png",
    description: "how we dream about our future",
    price: 9.99,
  },
];
export default breakfast;
