var dinner = [
  {
    id: "13",
    name: "Baked Chicken",
    category: "dinner",
    img: "https://i.postimg.cc/NFNrXcDd/dinner1.png",
    description: "how we dream about our future",
    price: 9.99,
  },
  {
    id: "14",
    name: "Lemoni Selmon Piccata",
    category: "dinner",
    img: "https://i.postimg.cc/kGVxN0Pc/dinner2.png",
    description: "how we dream about our future",
    price: 10.99,
  },
  {
    id: "15",
    name: "Garlic Butter Baked Salmons",
    category: "dinner",
    img: "https://i.postimg.cc/vmBkFmrH/dinner3.png",
    description: "how we dream about our future",
    price: 6.99,
  },
  {
    id: "16",
    name: "French Fire With Cheese",
    category: "dinner",
    img: "https://i.postimg.cc/gJyvgVxw/dinner4.png",
    description: "how we dream about our future",
    price: 8.99,
  },
  {
    id: "17",
    name: "Pork Tendiro",
    category: "dinner",
    img: "https://i.postimg.cc/FFDS1s3Q/dinner5.png",
    description: "how we dream about our future",
    price: 12.99,
  },
  {
    id: "18",
    name: "Salmon with Grapefruit and Green salad",
    category: "dinner",
    img: "https://i.postimg.cc/qM670kGw/dinner6.png",
    description: "how we dream about our future",
    price: 9.99,
  },
];
export default dinner;
