var lunch = [
  {
    id: "7",
    category: "lunch",
    name: "Healthy Meal Plan",
    img: "https://i.postimg.cc/bYFms2GQ/lunch1.png",
    description: "how we dream about our future",
    price: 23.99,
  },
  {
    id: "8",
    category: "lunch",
    name: "Fried Chicken Beneta",
    img: "https://i.postimg.cc/CLTmGpN1/lunch2.png",
    description: "how we dream about our future",
    price: 10.99,
  },
  {
    id: "9",
    name: "Tarragol-Rubble-Salmon",
    category: "lunch",
    img: "https://i.postimg.cc/vmrQms3V/lunch3.png",
    description: "how we dream about our future",
    price: 6.99,
  },
  {
    id: "10",
    name: "Indian Lunch",
    category: "lunch",
    img: "https://i.postimg.cc/mgb3jQ5z/lunch4.png",
    description: "how we dream about our future",
    price: 8.99,
  },
  {
    id: "11",
    name: "Beef Stick",
    category: "lunch",
    img: "https://i.postimg.cc/Kjx4b5Lt/lunch5.png",
    description: "how we dream about our future",
    price: 12.99,
  },
  {
    id: "12",
    name: "Honey-Soi-Glazed",
    category: "lunch",
    img: "https://i.postimg.cc/d35QYcJK/lunch6.png",
    description: "how we dream about our future",
    price: 9.99,
  },
];
export default lunch;
